
services:
 app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    networks:
      - mynet

 pgadmin:
    image: "elestio/pgadmin"
    environment:
      PGADMIN_DEFAULT_EMAIL: php@php.com
      PGADMIN_DEFAULT_PASSWORD: postgres
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - mynet

 database:
    image: "postgres"
    environment:
      PGHOST: database
      PGDATABASE: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: itachi007
    ports:
     - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
     - mynet

networks:
  mynet:
    driver: bridge
       
      
  
   

     
    
